### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by entmike** [osisoft/sample-adh-authentication_client_credentials_simple-postman#8]
Dead link referenced in your `README.md`:

> Register a [Client-Credentials Client](https://datahub.connect.aveva/clients) in your AVEVA Data Hub tenant and create a client secret to use in the configuration of this sample.

[https://datahub.connect.aveva/clients](https://datahub.connect.aveva/clients) seems inaccessible.

**Comment by cbardini** [comment]
Link fixed and merged
